# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d06080234024fe60e4429750e40d333d4a5e82dec4fcf05cb3ffe1b404e41c49b5d87fdfa45f667ff4985e730ab36044c93e19bd92965165be3d70f15ff3b93

test:
  secret_key_base: 3d390841ae95276ae4ddba4e149054cceab1d9ccb9912583a576ae8ef4a09311a6529f1492b48690dadf3b2bab671cd4e767230361a21020f4ffb1f4cd485eb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
